### ISSUE TITLE
Ignoring files like  #-aws-billing-detailed-line-items-with-resources-and-tags-year-month.csv.zip 

### ISSUE THREAD

**Issue by SMR39** [jonbrouse/docker-ice#11]
Hi, 

I don't understand why the application ignores the files with resources and tags and only process the files which are like "aws-billing-detailed-line-items-year-month.csv.zip".

The breakdown tab is not displayed in the ice reader although I gave the correct tag `user:name`
Is this because it couldnt process the files with tags and resources ?  The billing file has the tag in the header as separate column .
Any suggestions would be helpful.

`ice_1   | 2016-04-06 22:44:48,609 [com.netflix.ice.processor.BillingFileProcessor] INFO  processor.BillingFileProcessor  - ignoring file 522992507969-aws-billing-detailed-line-items-with-resources-and-tags-2014-12.csv.zip
ice_1   | 2016-04-06 22:44:48,609 [com.netflix.ice.processor.BillingFileProcessor] INFO  processor.BillingFileProcessor  - ignoring file 522992507969-aws-billing-detailed-line-items-with-resources-and-tags-2015-01.csv.zip
ice_1   | 2016-04-06 22:44:48,609 [com.netflix.ice.processor.BillingFileProcessor] INFO  processor.BillingFileProcessor  - ignoring file 522992507969-aws-billing-detailed-line-items-with-resources-and-tags-2015-02.csv.zip
ice_1   | 2016-04-06 22:44:48,609 [com.netflix.ice.processor.BillingFileProcessor] INFO  processor.BillingFileProcessor  - ignoring file 522992507969-aws-billing-detailed-line-items-with-resources-and-tags-2015-03.csv.zip
ice_1   | 2016-04-06 22:44:48,609 [com.netflix.ice.processor.BillingFileProcessor] INFO  processor.BillingFileProcessor  - ignoring file 522992507969-aws-billing-detailed-line-items-with-resources-and-tags-2015-04.csv.zip`

**Comment by jonbrouse** [comment]
This should probably be a [teevity/ice issue](https://github.com/Teevity/ice/issues)

**Comment by nfonrose** [comment]
Yes, it's probably an Ice configuration file issue.

--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
https://teevity.com - Cloud Costs Analytics built on NetflixOSS
twitter - @nfonrose / @teevity
