### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by pexaorj** [jonbrouse/docker-ice#12]
Could you can add to your code of "docker-compose.yml" template

 -Duser.timezone=<SET YOUR TIMEZONE HERE>
I´m using gmt-3 to Brazil

I take some time to find this option, i think that can help some other peoples :+1:

**Comment by jonbrouse** [comment]
Sorry for the delay. I've added `-Duser.timezone=<Your Timezone ie America/New_York>` to the compose file.
