### ISSUE TITLE
docker-compose failing on new instance types - https://github.com/Netflix/ice/issues/125

### ISSUE THREAD

**Issue by mpodber1971** [jonbrouse/docker-ice#16]
can a patch be created to handle this?

**Comment by mpodber1971** [comment]
error message:

ice_1    | | Error 2016-05-18 14:49:26,180 [localhost-startStop-1] ERROR BootStrap  - Startup failed
ice_1    | Message: failed to poll reservation prices for /home/centos/docker-ice/ice_processor/reservation_prices.threeyear.MEDIUM (No such file or directory)

**Comment by mpodber1971** [comment]
still receiving this error message: Message: /home/centos/docker-ice/ice_processor/reservation_prices.threeyear.LIGHT (No such file or directory)

any update on this?

**Comment by jonbrouse** [comment]
Sorry I have not had a chance to work on this repo in a while. I plan trying to get to it soon.

**Comment by jonbrouse** [comment]
I think is more related to the Ice application. Teevity has picked it up and could potentially push updates.
