### ISSUE TITLE
docker-compose up failing

### ISSUE THREAD

**Issue by gaborveres-planorama** [jonbrouse/docker-ice#17]
This is a brand new Ubuntu 14.04 on EC2, followed the guid and got

```
ice_1    | | Loading Grails 2.4.4
ice_1    | | Configuring classpath
ice_1    | | Downloading: joda-time/joda-time/maven-metadata.xml
ice_1    | | Downloading: joda-time/joda-time/maven-metadata.xml
ice_1    | | Downloading: joda-time/joda-time/2.9.4/joda-time-2.9.4.pom
ice_1    | | Downloading: joda-time/joda-time/2.9.4/joda-time-2.9.4.jar
ice_1    | | Running pre-compiled script
ice_1    | | Script 'Timezone' not found, did you mean:
ice_1    |    1) Console
ice_1    |    2) CreateIntegrationTest
ice_1    |    3) SetVersion
ice_1    |    4) Interactive
ice_1    |    5) CreateController
ice_1    | > Please make a selection or enter Q to quit: > Please make a selection or enter Q to quit: > Please make a selection or enter Q to quit: > Please make a selection or enter Q to quit: > Please make a selection or enter Q to quit: | Error Selection not found.
dockerice_ice_1 exited with code 1
```

Seems like Grails(?) pops up an interactive prompt which causes the container start to fail. Any ideas? Thanks!

**Comment by ankush-grover-3pg** [comment]
Facing the same issue.

docker-compose up
Starting dockerice_ice_1
Starting dockerice_nginx_1
Attaching to dockerice_ice_1, dockerice_nginx_1
ice_1    | | Loading Grails 2.4.4
ice_1    | | Configuring classpath
\
ice_1    | | Running pre-compiled script
ice_1    | | Script 'Timezone' not found, did you mean:
ice_1    |    1) Console
ice_1    |    2) CreateIntegrationTest
ice_1    |    3) SetVersion
ice_1    |    4) Interactive
ice_1    |    5) CreateController
ice_1    | > Please make a selection or enter Q to quit: > Please make a selection or enter Q to quit: > Please make a selection or enter Q to quit: > Please make a selection or enter Q to quit: > Please make a selection or enter Q to quit: | Error Selection not found.
dockerice_ice_1 exited with code 1

**Comment by ankush-grover-3pg** [comment]
Issue was related to Timezone values not filled in docker-compose.yml file. For ex

-Duser.timezone=Asia/Kolkata

**Comment by minac** [comment]
The problem was exactly what @ankush-grover-3pg said. I would suggest adding this bit to the readme so the issue can be closed.

**Comment by jonbrouse** [comment]
Time zone was added with commit [40135e532156196ca6d5e1cf19b462237b343da7](https://github.com/jonbrouse/docker-ice/commit/40135e532156196ca6d5e1cf19b462237b343da7#diff-3b86333cecc248902992faff6a00fd8a). Today I updated the README.md with [instructions to configure the time zone.](https://github.com/jonbrouse/docker-ice/commit/b35afe5dab07ca4f5cc23d94ca2691bfb60793ce#diff-04c6e90faac2675aa89e2176d2eec7d8). Closing the issue.
