### ISSUE TITLE
URL is opening  but nothing is visible

### ISSUE THREAD

**Issue by prasenforu** [jonbrouse/docker-ice#18]
Nothing is visible 

![image](https://cloud.githubusercontent.com/assets/19322497/22094618/a107285c-de34-11e6-9ec6-080016a466fd.png)

**Comment by jonbrouse** [comment]
Ensure that your instance can get to the billing S3 bucket. Let me know if you are still having an issue.

**Comment by jonbrouse** [comment]
I'm closing, please open a new issue if you are still having problems.
