### ISSUE TITLE
OutOfMemory Exception

### ISSUE THREAD

**Issue by utsav2307** [jonbrouse/docker-ice#23]
I am trying to run ice, but continuously getting OutOfMemory Exception. 

<img width="857" alt="screen shot 2017-07-19 at 2 04 47 pm" src="https://user-images.githubusercontent.com/22631337/28358176-789a4dd2-6c8b-11e7-9f1a-1f652cd95fe9.png">

I even tried setting JVM options in docker-compose file but still its not working.

<img width="541" alt="screen shot 2017-07-19 at 2 10 27 pm" src="https://user-images.githubusercontent.com/22631337/28358317-0e674a40-6c8c-11e7-872d-9657ce2fa5d8.png">

How can I resolve this error?

**Comment by jonbrouse** [comment]
Ice is launched via grails and so the entrypoint isn't `java` which is why adding the options to the `command` didn't work.

```
ENTRYPOINT ["/opt/ice/grailsw"]
```
The Dockerfile contains `ARG JAVA_OPTS`. You can pass in options via the `JAVA_OPTS` environment variable.

```
 environment:
  - JAVA_OPTS=-Xms4G -Xmx5G
```
You might need quotes around the actual options.

**Comment by palmerit** [comment]
I was running into the same issue, and had previously tried both of the workarounds listed here.  neither worked.   This did:

`  environment:
    - GRAILS_OPTS=-server -Xmx4G -Xms1G -Dfile.encoding=UTF-8`

Let me know if it helps.

**Comment by utsav2307** [comment]
Yes, this worked, thanks a lot
