### ISSUE TITLE
Not working, nginx page error

### ISSUE THREAD

**Issue by cleitondomazak** [jonbrouse/docker-ice#32]
I'm running the last docker-compose, on Ubuntu and MacOS, with Docker 17.12 and Compose 1.18, in both SO. 

But when I access http://localhost/ice/dashboard/summary a Nginx page error happen.

![screen shot 2018-01-17 at 22 31 27](https://user-images.githubusercontent.com/8502873/35074688-357792b4-fbd6-11e7-90aa-bf56c3842890.png)

I check the container output, and no errors happen.

Even when I execute a curl inside Ice container on 8080 port, does not respond.

**Comment by aditi10** [comment]
It may be because your ice docker container is still executing in the background. Nginx is unable to redirect http://localhost:80 to /ice/dashboard/summary. So let your ice docker execute successfully then you may not get this error.

**Comment by jonhadfield** [comment]
Try adding this to your ice.properties file:
`ice.billing_s3bucketregion=<your bucket region>`  

I had the same issue and found an update to ice itself introduced that requirement:
https://github.com/Teevity/ice/issues/271

**Comment by cleitondomazak** [comment]
I added this parameter @jonhadfield .

![image](https://user-images.githubusercontent.com/8502873/36811353-37c73c44-1cac-11e8-8f55-5580c9b0d36e.png)

I did another test, changing the ICE_VERSION to 1.1.1(in Dockerfile), and sound OK with this version.
