### ISSUE TITLE
AWS report format

### ISSUE THREAD

**Issue by yevgeniyo** [jonbrouse/docker-ice#34]
Hi,

You re asking for format: <accountid>-aws-billing-detailed-line-items-<year>-<month>.csv.zip

From AWS documentation I can see that reports are stored like:
<example-report-prefix>/<example-report-name>/20160101-20160131/<123456789>/<example-report-name>-<1>.csv.<zip>

1. The question is, how AWS can generate format you asking automatically?
2. After finishing of reports generating I got 4 files: 
xyz-1.csv.zip
xyz-2.csv.zip
xyz-3.csv.zip
xyz-Manifest.json
What should I do with them?

**Comment by nfonrose** [comment]
Hello Yevgeniy,

What you are referring to are the CUR reports.

ICE does not support the CUR reports yet (this is coming soon).
For now, you need to active the Programmatic Billing Reports.

https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/billing-reports-other.html

Nicolas



--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
https://teevity.com - Cloud Costs Analytics built on NetflixOSS
twitter - @nfonrose / @teevity

**Comment by yevgeniyo** [comment]
Hi Nicolas,

Appreciate your help, thank you

BR, Yevgeniy

**Comment by jonbrouse** [comment]
Thank you @nfonrose
