### ISSUE TITLE
Cant start web

### ISSUE THREAD

**Issue by yevgeniyo** [jonbrouse/docker-ice#36]
Getting these errors:

ice_1    | 2018-04-17 15:55:58,917 [main] INFO  http11.Http11NioProtocol  - Initializing ProtocolHandler ["http-nio-8080"]
ice_1    | 2018-04-17 15:55:58,937 [main] INFO  net.NioSelectorPool  - Using a shared selector for servlet write/read
ice_1    | 2018-04-17 15:55:58,951 [main] INFO  core.StandardService  - Starting service Tomcat
ice_1    | 2018-04-17 15:55:58,951 [main] INFO  core.StandardEngine  - Starting Servlet Engine: Apache Tomcat/8.0.20
ice_1    | 2018-04-17 15:55:59,061 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesStatic] to [false] as the property does not exist.
ice_1    | 2018-04-17 15:55:59,062 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesStopThreads] to [false] as the property does not exist.
ice_1    | 2018-04-17 15:55:59,063 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesStopTimerThreads] to [false] as the property does not exist.
ice_1    | 2018-04-17 15:55:59,063 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesHttpClientKeepAliveThread] to [true] as the property does not exist.
ice_1    | 2018-04-17 15:55:59,070 [localhost-startStop-1] INFO  startup.ContextConfig  - No global web.xml found
ice_1    | 2018-04-17 15:55:59,168 [localhost-startStop-1] INFO  [localhost].[/ice]  - No Spring WebApplicationInitializer types detected on classpath
ice_1    | 2018-04-17 15:55:59,190 [localhost-startStop-1] INFO  [localhost].[/ice]  - Initializing Spring root WebApplicationContext
ice_1    | 2018-04-17 15:56:03,007 [localhost-startStop-1] INFO  context.GrailsConfigUtils  - [GrailsContextLoader] Grails application loaded.
ice_1    | 2018-04-17 15:56:03,031 [localhost-startStop-1] INFO  BootStrap  - Starting ice...
ice_1    | 2018-04-17 15:56:04,365 [localhost-startStop-1] INFO  common.AwsUtils  - file not found in s3 /mnt/ice_processor/reservation_prices.threeyear.LIGHT
ice_1    | 2018-04-17 15:56:04,376 [localhost-startStop-1] INFO  common.AwsUtils  - file not found in s3 /mnt/ice_processor/reservation_prices.threeyear.MEDIUM
ice_1    | 2018-04-17 15:56:04,383 [localhost-startStop-1] INFO  common.AwsUtils  - file not found in s3 /mnt/ice_processor/reservation_prices.threeyear.HEAVY
ice_1    | 2018-04-17 15:56:04,391 [localhost-startStop-1] INFO  common.AwsUtils  - file not found in s3 /mnt/ice_processor/reservation_prices.threeyear.FIXED

Can you please advice?

**Comment by yevgeniyo** [comment]
Hi Nicolas,

I have passed it, but now my dashboard is empty. 
All data is stored under s3, but cant be shown via the dashboard.

No account, region, product, operation, usage type

Sorry for dummy questions =(

**Comment by nfonrose** [comment]
Ok. In order to help, we need some more info about the execution that led
to this situation.
Can you aws s3 ls the content of:

   - your billing bucket
   - your ice working bucket

Sorry for dummy questions =(


No pb :-)

--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
https://teevity.com - Cloud Costs Analytics built on NetflixOSS
twitter - @nfonrose / @teevity

**Comment by yevgeniyo** [comment]
Hi Nicolas,
Thank you for quick responses, really appreciate it.
Bellow my configuration and list of objects inside of bucket:

List of bucket objects:

2018-03-08 18:12:30    4274154 123456789-aws-billing-detailed-line-items-2018-03.csv.zip
2018-03-08 18:12:45   23331936 123456789-aws-billing-detailed-line-items-with-resources-and-tags-2018-03.csv.zip
2018-03-08 18:12:40          4 aws-programmatic-access-test-object
2018-04-18 15:23:04          4 reservation_prices.threeyear.FIXED
2018-04-18 15:23:04     393160 reservation_prices.threeyear.HEAVY
2018-04-18 15:23:04          4 reservation_prices.threeyear.LIGHT
2018-04-18 15:23:04          4 reservation_prices.threeyear.MEDIUM

ice.properties

ice.processor=true
ice.reader=true
ice.reservationCapacityPoller=false
ice.reservationPeriod=threeyear
ice.reservationUtilization=MEDIUM
ice.highstockUrl=https://code.highcharts.com/stock/4.2.1/highstock.js
ice.urlPrefix=
ice.fromEmail=
ice.ondemandCostAlertThreshold=250
ice.ondemandCostAlertEmails=
ice.billing_s3bucketname=billing-reports
ice.billing_s3bucketregion=us-east-1
ice.billing_s3bucketprefix=
the second bucket.
ice.billing_payerAccountId=123456789
ice.startmillis=1364774400000
ice.companyName=Incapsula
ice.work_s3bucketname=billing-reports
ice.work_s3bucketprefix=
ice.processor.localDir=/mnt/ice_processor
ice.reader.localDir=/mnt/ice_reader
ice.monthlycachesize=12
ice.account.prod=123456789

ice.owneraccount.account1.role=ice
ice.owneraccount.account2.role=ice
ice.owneraccount.account5.role=ice

ice.owneraccount.account1.externalId=123456789
ice.owneraccount.account2.externalId=
ice.owneraccount.account5.externalId=

**Comment by nfonrose** [comment]
You have forgotten the content  (list of files) inside your "ice working
bucket"

--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
https://teevity.com - Cloud Costs Analytics built on NetflixOSS
twitter - @nfonrose / @teevity

**Comment by yevgeniyo** [comment]
i have the same bucket for this purpose.....should it be separate?

**Comment by nfonrose** [comment]
Yes, it's much cleaner to use two separate buckets. Not sure this is the
cause of the issue, but it sure doesn't help

--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
https://teevity.com - Cloud Costs Analytics built on NetflixOSS
twitter - @nfonrose / @teevity

**Comment by jonbrouse** [comment]
No response.. closing
