### ISSUE TITLE
dockerice_ice_1 exited with code 0 

### ISSUE THREAD

**Issue by pleegor** [jonbrouse/docker-ice#6]
Hi,

First of all great work on docker-ice!

I am trying to setup container however, when I ran `docker-compose up` I got `dockerice_ice_1 exited with code 0` when I as looking more into the output I found the following error:

`ice_1   | 2016-02-25 00:07:03,793 [localhost-startStop-1] INFO  BootStrap  - Starting ice...
ice_1   | | Error com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: *********************), S3 Extended Request ID: 6rWB48bERymibD2hNItWcUck/xF+S1kW8+cxwHgyzeYIOFJlv15A5wRjEd0jF0R4ZK2mHSA6/Qw=`

Is there a specific permission for account that is used in ice? if there is could you please advise on that?

**Comment by jonbrouse** [comment]
Looks like you might not have the s3 bucket configured correctly.

**Comment by jonbrouse** [comment]
Are you still having issues with this? I'm going to close it since I haven't heard back in a week.

**Comment by pl33g0r** [comment]
I should have an update later today...

**Comment by pl33g0r** [comment]
@jonbrouse 

Can you please keep this issue open (sorry it slipped out of my hands)? I think I fixed s3 issue by reconfiguring bucket; however I got a new set of errors...
`ice_1   | ^    745 | run . . . . . . . . . . . . . .  in java.lang.Thread
ice_1   | | Error java.lang.RuntimeException: failed to poll reservation prices for null
ice_1   | | Error 	at com.netflix.ice.basic.BasicReservationService.init(BasicReservationService.java:110)
ice_1   | | Error 	at com.netflix.ice.processor.ProcessorConfig.<init>(ProcessorConfig.java:95)
ice_1   | | Error 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
ice_1   | | Error 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
ice_1   | | Error 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
ice_1   | | Error 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
ice_1   | | Error 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
ice_1   | | Error 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
ice_1   | | Error 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
ice_1   | | Error 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
ice_1   | | Error 	at BootStrap$_closure1.doCall(BootStrap.groovy:186)
ice_1   | | Error 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ice_1   | | Error 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
ice_1   | | Error 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ice_1   | | Error 	at java.lang.reflect.Method.invoke(Method.java:606)
ice_1   | | Error 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
ice_1   | | Error 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
ice_1   | | Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
ice_1   | | Error 	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
ice_1   | | Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
ice_1   | | Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1081)
ice_1   | | Error 	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
ice_1   | | Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
ice_1   | | Error 	at groovy.lang.Closure.call(Closure.java:423)
ice_1   | | Error 	at groovy.lang.Closure.call(Closure.java:417)
ice_1   | | Error 	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
ice_1   | | Error 	at grails.util.Environment.executeForEnvironment(Environment.java:320)
ice_1   | | Error 	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
ice_1   | | Error 	at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
ice_1   | | Error 	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:78)
ice_1   | | Error 	at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:110)
ice_1   | | Error 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
ice_1   | | Error 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4728)
ice_1   | | Error 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5162)
ice_1   | | Error 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
ice_1   | | Error 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
ice_1   | | Error 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
ice_1   | | Error 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
ice_1   | | Error 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
ice_1   | | Error 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
ice_1   | | Error 	at java.lang.Thread.run(Thread.java:745)
ice_1   | | Error 2016-03-03 18:58:50,314 [localhost-startStop-1] ERROR BootStrap  - Startup failed
ice_1   | Message: failed to poll reservation prices for null
ice_1   |     Line | Method
ice_1   | ->>  110 | init                             in com.netflix.ice.basic.BasicReservationService
ice_1   | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
ice_1   | |     95 | <init>                           in com.netflix.ice.processor.ProcessorConfig
ice_1   | |    186 | doCall . . . . . . . . . . . . . in BootStrap$_closure1
ice_1   | |    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
ice_1   | |    320 | executeForEnvironment . . . . .  in     ''
ice_1   | |    296 | executeForCurrentEnvironment     in     ''
ice_1   | |    262 | run . . . . . . . . . . . . . .  in java.util.concurrent.FutureTask
ice_1   | |   1145 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
ice_1   | |    615 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
ice_1   | ^    745 | run                              in java.lang.Thread`

**Comment by jonbrouse** [comment]
No problem keeping the issue open. Could you supply your config file with your aws keys removed?

**Comment by pl33g0r** [comment]
this is what I have: 
`
ice:
  image: jonbrouse/ice:latest
  command: |
    -Djava.net.preferIPv4Stack=true
    -Djava.net.preferIPv4Addresses
    -Dice.s3AccessKeyId="accesskey"
    -Dice.s3SecretKey="sercet_key"
    run-app
  volumes:
    - ./ice/assets/ice.properties:/opt/ice/src/java/ice.properties
nginx:
  image: jonbrouse/ice-proxy:latest
  ports:
    - "80:80"
  links:
    - ice:ice

**Comment by jonbrouse** [comment]
okay, how about your `./ice/assets/ice.properties`

**Comment by pl33g0r** [comment]
https://gist.github.com/pl33g0r/5025717902153a21addc

**Comment by pexaorj** [comment]
I Got the same error, reconfigure all my s3 bucket and still have this error:

ice_1   | 2016-04-07 15:31:24,234 [localhost-startStop-1] INFO  BootStrap  - Starting ice...
ice_1   | | Error com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: DAE952C11FEE3CA7), S3 Extended Request ID: LpAzFffXyMNgjN09ByThrqVJdMZzS+hbAO4BffDEQu2DBve43ETxcAQ1f6CpEFA/Ae+fIsA4i2E=
ice_1   | | Error       at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1077)
ice_1   | | Error       at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:725)
ice_1   | | Error       at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:460)
ice_1   | | Error       at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
ice_1   | | Error       at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3710)
ice_1   | | Error       at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1146)
ice_1   | | Error       at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1018)
ice_1   | | Error       at com.netflix.ice.common.AwsUtils.download(AwsUtils.java:334)
ice_1   | | Error       at com.netflix.ice.common.AwsUtils.download(AwsUtils.java:329)
ice_1   | | Error       at com.netflix.ice.common.AwsUtils.downloadFileIfNotExist(AwsUtils.java:317)
ice_1   | | Error       at com.netflix.ice.basic.BasicReservationService.init(BasicReservationService.java:101)
ice_1   | | Error       at com.netflix.ice.processor.ProcessorConfig.<init>(ProcessorConfig.java:95)
ice_1   | | Error       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
ice_1   | | Error       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
ice_1   | | Error       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
ice_1   | | Error       at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
ice_1   | | Error       at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
ice_1   | | Error       at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
ice_1   | | Error       at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
ice_1   | | Error       at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
ice_1   | | Error       at BootStrap$_closure1.doCall(BootStrap.groovy:186)
ice_1   | | Error       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ice_1   | | Error       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
ice_1   | | Error       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ice_1   | | Error       at java.lang.reflect.Method.invoke(Method.java:606)
ice_1   | | Error       at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
ice_1   | | Error       at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
ice_1   | | Error       at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
ice_1   | | Error       at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
ice_1   | | Error       at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
ice_1   | | Error       at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1081)
ice_1   | | Error       at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
ice_1   | | Error       at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
ice_1   | | Error       at groovy.lang.Closure.call(Closure.java:423)
ice_1   | | Error       at groovy.lang.Closure.call(Closure.java:417)
ice_1   | | Error       at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
ice_1   | | Error       at grails.util.Environment.executeForEnvironment(Environment.java:320)
ice_1   | | Error       at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
ice_1   | | Error       at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
ice_1   | | Error       at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:78)
ice_1   | | Error       at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:110)
ice_1   | | Error       at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
ice_1   | | Error       at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4728)
ice_1   | | Error       at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5162)
ice_1   | | Error       at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
ice_1   | | Error       at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
ice_1   | | Error       at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
ice_1   | | Error       at java.util.concurrent.FutureTask.run(FutureTask.java:262)
ice_1   | | Error       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
ice_1   | | Error       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
ice_1   | | Error       at java.lang.Thread.run(Thread.java:745)
ice_1   | | Error 2016-04-07 15:31:25,648 [localhost-startStop-1] ERROR BootStrap  - Startup failed
ice_1   | Message: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: DAE952C11FEE3CA7)
ice_1   |     Line | Method
ice_1   | ->> 1077 | handleErrorResponse              in com.amazonaws.http.AmazonHttpClient
ice_1   | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by jonbrouse** [comment]
@pexaorj check your aws key

```
ERROR BootStrap - Startup failed
Message: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: DAE952C11FEE3CA7)
```

**Comment by jonbrouse** [comment]
@pl33g0r

**Comment by pexaorj** [comment]
Hello @jonbrouse, Its sounds very strange, because when I remove that docker container and Install ice from source code, I use the same key and all works.
So I think that the problem is not my key, but another thing.

by the way, thaks a lot for the help :)

**Comment by BenjaminDavison** [comment]
(Really late to this)

We managed to get the same error, we hadn't set any value for the output bucket.

**Comment by jonbrouse** [comment]
This is an older issue. Please create a new issue if you are still having a problem.
