### ISSUE TITLE
Is there any thing wrong with the tutorial?

### ISSUE THREAD

**Issue by khoi-thinh** [jonbrouse/docker-ice#8]
Hi jonbrouse!
I just found out about this tools by chances and i just want to give it a try.
But when executing this command,
cp docker-compose-template.yml docker-compose.yml. It said: "cp: cannot stat ‘docker-compose-template.yml’: No such file or directory"
And when it comes to docker-compose.yml, i tried to create one file but it didn't work when executing.
It said:  
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here.
So could you clarify more about this tutorial?
I really appreciate it.

**Comment by pl33g0r** [comment]
dod you run `git clone <repo url>` before you started copying files?

**Comment by thinhduckhoi** [comment]
Thank you so much for a quick reply.
I got through it.
http://www.upsieutoc.com/images/2016/03/03/build-error.jpg
But i don't know if this was error or not.
Could you please take a look at it and help me out?

**Comment by jonbrouse** [comment]
From the README

> After following these directions you should be able to connect to your server's IP address or FQDN over port 80 and access the Ice application.

**Comment by jonbrouse** [comment]
Also, from your dump:

`There is insufficient memory for the Java Runtime Environment to continue.`

**Comment by thinhduckhoi** [comment]
So how to fix this?
`There is insufficient memory for the Java Runtime Environment to continue.`
I was testing this using AWS Instance EC2 (t2.micro with 1gb ram and 20gb disk).

**Comment by puvitsingh** [comment]
you can scale up your aws instance.  

What was the answer to the "cannot stat ‘docker-compose-template.yml’:" issue?

**Comment by jonbrouse** [comment]
If you are still having issues with the template file, please trying reading through the README. If you still are running into a problem, please open a new issue
