### ISSUE TITLE
I got stuck when starting container

### ISSUE THREAD

**Issue by khoi-thinh** [jonbrouse/docker-ice#9]
Hi Jonbrouse!
So last time when i tested this ice docker using instance EC2 with 1GB ram, seems like it was out of memory.
So this time i tried using another server featuring CentOS 7.2, 8GB ram and 30GB Hard-disk (this was cloud computing, noit physical )
Then i followed the tutorial smoothly until issuing the command "docker-compose up".
This time the error was not about "memory" but something related to "connecting to upstream"
Can you take a look at it and tell me what was wrong? You can see my screenshot about it.
http://www.upsieutoc.com/images/2016/03/08/error.jpg

And one more question: ""After following these directions you should be able to connect to your server's IP address or FQDN over port 80 and access the Ice application"". But i checked the Dockerfile's content and saw just port 8080 exposed. Why was that?

**Comment by jonbrouse** [comment]
Cleaning up issues, please open a new ticket if you are still having problems.
